### ISSUE TITLE
Wrong owner in /dev/pts

### ISSUE THREAD

**Issue by Gavus** [containers/toolbox#1016]
**Describe the bug**
My /dev/pts/ inside a toolbox have the owner set as root. Outside of toolbox they are owned by my user.

**Steps how to reproduce the behaviour**
1. Enter a running toolbox with at least two sessions.
2. Start python3.
3. Enter: "import io; tty=io.TextIOWrapper(open("/dev/pts/x", "r+b", buffering=0))" (replace x with one of the session numbers).

**Expected behaviour**
No error.

**Actual behaviour**
"PermissionError: [Errno 13] Permission denied: '/dev/pts/x'.

**Output of `toolbox --version` (v0.0.90+)**
 `toolbox version 0.0.99.3`

**Toolbox package info (`Github`)**
tag 0.0.99.3

**Output of `podman version`**
e.g.,
```
Version:            3.0.1
RemoteAPI Version: ?
Go Version:         ?
OS/Arch:            linux/amd64
``

**Info about your OS**
Debian 11 (bullseye)

**Additional context**
I noticed this problem when using the python debugger module pudb, wanting to display the tui in another terminal.

**Comment by Ramblurr** [comment]
This also prevents the use of `emacsclient --tty`:

```
$ emacsclient --tty
*ERROR*: Could not open file: /dev/pts/1
$ sudo chown ramblurr /dev/pts/1
$ emacsclient --tty
<emacs opens>
```

**Comment by swick** [comment]
This also prevents the mutter kvm test suit from running:

`qemu-system-x86_64: -chardev file,id=console,path=/proc/self/fd/2`

@debarshiray

**Comment by debarshiray** [comment]
I filed https://github.com/containers/podman/issues/17701 for some clarifications and advice.

**Comment by debarshiray** [comment]
> I filed [containers/podman#17701](https://github.com/containers/podman/issues/17701) for some clarifications and advice.

That got renamed to https://github.com/containers/crun/issues/1158

**Comment by debarshiray** [comment]
> This also prevents the use of `emacsclient --tty`:
> 
> ```
> $ emacsclient --tty
> *ERROR*: Could not open file: /dev/pts/1
> $ sudo chown ramblurr /dev/pts/1
> $ emacsclient --tty
> <emacs opens>
> ```

I suspect that this is similar to the problem @dustymabe has been facing with `gpg-agent` and `pinentry` in https://github.com/containers/toolbox/issues/568

Even if you fix the user ownership of the pseudo-terminal device (ie., the output of `tty(1)`), running `emacsclient --tty` inside the container doesn't open Emacs in the same terminal.  Instead it opens it on a different host terminal whose `tty(1)` accidentally happens to match the container's.

I use Emacs, but not in a server-client mode, so I am not entirely sure, but I think that the client should open in the same terminal where I typed `emacsclient --tty`.  At least that's what happens on the host.

It's an accident because the pseudo-terminal devices inside the container aren't the same as on the host.  They are totally different because the container has it's own `devpts` file system at `/dev/pts` within its mount and user namespaces.

**Comment by debarshiray** [comment]
> This also prevents the mutter kvm test suit from running:
> 
> `qemu-system-x86_64: -chardev file,id=console,path=/proc/self/fd/2`

Does https://github.com/containers/crun/pull/1159 help?

I can try to run the mutter test suite myself, but it will take some time.  :)

**Comment by swick** [comment]
Always fun to test stuff like this on silverblue. Yes, works like a charm. Thanks!

**Comment by debarshiray** [comment]
> Always fun to test stuff like this on silverblue. Yes, works like a charm. Thanks!

Yes, I can imagine.  I locally rebuild the RPM with the relevant patch and force it onto my base image.  :P

Thanks for testing it, @swick !

**Comment by debarshiray** [comment]
I am closing this on the assumption that the `emacsclient --tty` problem is unrelated to the other two problems reported here.

Please leave a comment or open an issue if you have reason to believe otherwise.
