### ISSUE TITLE
Running "toolbox list" is slow

### ISSUE THREAD

**Issue by Jacalz** [containers/toolbox#1027]
## Describe the bug
A clear and concise description of *what the bug is*. If possible, re-run the command(s) with `--log-level debug` and put the output here.
When I run the `toolbox list` command, it takes several seconds to complete. It seems especially slow because I only have two containers set up and having the laptop in power saver mode makes it even slower. On balanced power, the command takes about 2 seconds to complete and 5 seconds on power saver.

## Steps how to reproduce the behaviour
1. Set up one or two containers.
2. Run `toolbox list`.

## Expected behaviour
It should be more or less instant. I don't remember what it's called but there is some sort of time that has been agreed that anything slower will feel slow. I'd personally be happy with anything below one second.

## Actual behaviour
Takes between 2 and 5 seconds to complete.

### On power saver:
```
[jacob@kinoite jacob]$ time toolbox list
IMAGE ID      IMAGE NAME                                    CREATED
09cc3fe0e1d0  registry.fedoraproject.org/fedora-toolbox:35  12 days ago
54573228a6a3  registry.fedoraproject.org/fedora-toolbox:36  12 days ago

CONTAINER ID  CONTAINER NAME     CREATED      STATUS      IMAGE NAME
b00ea01e59e0  fedora-toolbox-35  7 days ago   configured  registry.fedoraproject.org/fedora-toolbox:35
33a95a74ebe3  fedora-toolbox-36  4 hours ago  configured  registry.fedoraproject.org/fedora-toolbox:36

real    0m5.231s
user    0m2.203s
sys     0m3.863s
```

### On balanced:
```
[jacob@kinoite jacob]$ time toolbox list
IMAGE ID      IMAGE NAME                                    CREATED
09cc3fe0e1d0  registry.fedoraproject.org/fedora-toolbox:35  12 days ago
54573228a6a3  registry.fedoraproject.org/fedora-toolbox:36  12 days ago

CONTAINER ID  CONTAINER NAME     CREATED      STATUS      IMAGE NAME
b00ea01e59e0  fedora-toolbox-35  7 days ago   configured  registry.fedoraproject.org/fedora-toolbox:35
33a95a74ebe3  fedora-toolbox-36  4 hours ago  configured  registry.fedoraproject.org/fedora-toolbox:36

real    0m2.436s
user    0m0.925s
sys     0m1.684s
```

## Output of `toolbox --version`
``` toolbox version 0.0.99.3 ```

## Toolbox package info (`rpm -q toolbox`)
``` toolbox-0.0.99.3-2.fc35.x86_64 ```

## Output of `podman version`
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

## Podman package info (`rpm -q podman`)
``` podman-3.4.4-1.fc35.x86_64 ```

## Info about your OS
Fedora Kinoite 35

## Additional context
The laptop in question is a Dell Latitude 7490 with 16GB ram, 4 core / 8 threads i5 8250U and a 256GB M.2 Sata SSD.
I don't believe the laptop to be a bottleneck in this specific issue.

**Comment by HarryMichal** [comment]
It's already been some time but at some point the performance of `podman images` (which is called together with `podman ps` under the hood) got significantly worse. Without delving into the internals of Podman, there isn't really much we can do.

I'm aware of a slight overhead caused by Toolbx (processing of results + printing) but that one is around 100-200ms (admittedly, that is still quite a lot for relatively trivial post-processing).

When it comes to the Balanced/Power saver profiles, compare the performance of Toolbx to the performance of other applications. Are they also significantly slower? Then there's little that Toolbx itself can do to make that better.

Out of curiosity, could you time the runtime of commands `podman images -a` and `podman ps -a`? I expect them to be slightly faster. Either try to execute them in series (images first) or compare them to `toolbox list -c|-i`.

**Comment by Jacalz** [comment]
> When it comes to the Balanced/Power saver profiles, compare the performance of Toolbx to the performance of other applications. Are they also significantly slower? Then there's little that Toolbx itself can do to make that better.

Hmm, good question. I admittedly hadn't thought too much about that. Compiling Go code gets significantly slower but everything else seems to behave well without noticing any big slowdown. It might just be that the very long tasks make the scheduling try to avoid "turboing" the CPU. Perhaps I, in hindsight, shouldn't have made the battery saver thing such a big part of the issue. Let's just say that it is 2x slower, and unbearably slow on power saver mode. As I run battery saver almost all the time, it gets very noticeable ;) 

> Out of curiosity, could you time the runtime of commands `podman images -a` and `podman ps -a`? I expect them to be slightly faster. Either try to execute them in series (images first) or compare them to `toolbox list -c|-i`.

Sure thing. I think you are right that podman contributes part (or most) of the slowness. I get this when running the first command (`podman images -a`):
```
[jacob@kinoite jacob]$ time podman images -a
REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
registry.fedoraproject.org/fedora-toolbox  35          09cc3fe0e1d0  12 days ago  497 MB
registry.fedoraproject.org/fedora-toolbox  36          54573228a6a3  12 days ago  496 MB

real    0m2.047s
user    0m0.818s
sys     0m1.537s
```

As you say, it is slightly faster but similar in speed to toolbox.
The second command (`podman ps -a`) is a lot faster:
```
[jacob@kinoite jacob]$ time podman ps -a
CONTAINER ID  IMAGE                                         COMMAND               CREATED      STATUS      PORTS       NAMES
b00ea01e59e0  registry.fedoraproject.org/fedora-toolbox:35  toolbox --log-lev...  7 days ago   Created                 fedora-toolbox-35
33a95a74ebe3  registry.fedoraproject.org/fedora-toolbox:36  toolbox --log-lev...  6 hours ago  Created                 fedora-toolbox-36

real    0m0.142s
user    0m0.040s
sys     0m0.038s
```

Running them directly after each other, I get this time (almost exactly the sum of them):
```
real    0m2.188s
user    0m0.856s
sys     0m1.604s
```

Would it make sense to switch to the second podman command for the list command?

**Comment by HarryMichal** [comment]
Each of these commands is for a different purpose. One lists your containers and the other your images. We need both.

I honestly don't know if there's something we can do to significantly affect the UX. An extreme measure could be to explicitly split the command and mimic Podman. But I'm personally opposed to the idea at the moment. Some minor tweaks could be done to lower the overhead caused by Toolbx but that will give us only minor results. Lastly, one could delve into Podman and try to speed-up `podman images`.

**Comment by Jacalz** [comment]
I agree with you. Seems like the most sensible conclusion. Do you want me to open an issue with podman?

**Comment by HarryMichal** [comment]
Sure!

**Comment by Jacalz** [comment]
Cool. I'll try to get one sorted later in the week then. I don't want to open an issue against an older version and then have it closed because of that.

**Comment by Jacalz** [comment]
Sorry for the wait. I had to wait for the Fedora 36 Beta to get easy access to the latest version of podman. The issue has been opened at https://github.com/containers/podman/issues/13755.

**Comment by vrothberg** [comment]
Podman v4.1 will ship with a new `--size` flag for `podman images`. `podman images --size=false` will stop Podman from calculating the image sizes. Ultimately we aim for optimizations in the storage backend but `--size=false` may be an alternative for `toolbox`.

If you encounter further performance regression in Podman, please report them early on.  We're working on benchmarks at the moment but performance regressions are sometimes hard to detect.

**Comment by debarshiray** [comment]
Thanks for tracking that down @vrothberg 

It turned out that we didn't have to use `podman images --size` in Toolbx, because,  soon after, @nalind fixed the [root](https://github.com/containers/storage/commit/d76b3606fc9ca975bf436379f91105f0fac1555f) [cause](https://github.com/containers/storage/pull/1197) in `containers/storage`, and the `--size` option was [even](https://github.com/containers/podman/commit/97f93dc78e61820196f2adcc06ab8ec145ef6703) [dropped](https://github.com/containers/podman/pull/13872) from Podman itself.

As happy an ending as one can imagine.  :)
