### ISSUE TITLE
Can't access /var/home directory

### ISSUE THREAD

**Issue by tazihad** [containers/toolbox#1172]
I can't access other users directory. I see only my user home directory.
Is there any option to mount other user home directory at /home or /var/home?

**Comment by debarshiray** [comment]
You can do your own bind mounts from the host from inside the Toolbx container.  The entire host filesystem is available at `/run/host`, and you can use `sudo mount --rbind ...`.

However, in this specific case, note that usually a non-root user is restricted from accessing the home directory of other users.  So, depending on the permissions on your host, you may or may not succeed, if you are using rootless Toolbx because it only has access to your own UID on the host.  You might have more luck trying rootful Toolbx.

**Comment by debarshiray** [comment]
Closing, because this isn't a bug in Toolbx per se.

Feel free to leave a comment, if you have reason to believe otherwise, or if you have further questions.

**Comment by matthiasclasen** [comment]
Fwiw, all the home directories show up in  /run/host/var/home (or /run/host/home, as it may be).
