### ISSUE TITLE
Toolbox command usability improvements

### ISSUE THREAD

**Issue by zerotri** [containers/toolbox#123]
Not wanting to encroach on your future design goals too much, I'd like to propose a change to the toolbox `create` and `enter` commands for usability and consistency.

the toolbox `rm` command is defined as:
**toolbox rm** [*--all*] [*--force*] [*CONTAINER*...]

whereas enter and create are defined:
**toolbox enter** [*--container NAME* | *-c NAME*] [*--release RELEASE* | *-r RELEASE*]
**toolbox create** [*--candidate-registry*] [*--container NAME* | *-c NAME*] [*--image NAME* | *-i NAME*] [*--release RELEASE* | *-r RELEASE*]

For ease of use and consistency, it would make sense to me to express container name through a non-named final argument, much as is done in `rm`. Using a named argument as above would make sense if there were any non-named arguments necessary for the command but as of yet there do not seem to be.

So what I'm proposing here would be:
**toolbox enter** [*--release RELEASE* | *-r RELEASE*] [*CONTAINER*...]
**toolbox create** [*--candidate-registry*] [*--image NAME* | *-i NAME*] [*--release RELEASE* | *-r RELEASE*] [*CONTAINER*...]

Where here the container name is simply implied when not given, much as it is now.

This simplifies entering containers from `toolbox enter --container sysutils` to `toolbox enter sysutils`.

I don't mind working on and submitting a PR for this, I'd love to get your thoughts on this first though.

**Comment by debarshiray** [comment]
Thanks for the feedback!

The command line interface certainly needs to be revisited and thought through. I can't say that they were particularly *designed* in any way. :)

There's some interest (see issue #128) in making `enter` a bit more flexible. eg., when there's just one container present. There are shorter aliases for `--container` and friends now, which help a bit with the typing.

Whatever we do, it would be good to have tab completion for Bash (see issue #59). Do you want to help with that?

Historically, what happened was that the `toolbox` command grew as a wrapper around `podman` and `buildah` to make them more accessible to people who weren't interested in the details of container technology and the innards of the OS. In it's simplest form you'd do `toolbox create` and `toolbox enter` and you'd be inside a container that looked just like your host OS. Then we added some flags to override some of the defaults, but if you wanted a peek under the hood at the containers and images themselves, you'd have to use `podman` itself. Then people started asking for aliases or wrappers to often used `podman` commands because they didn't want to be bothered with anything other than the `toolbox` command. That's how `list`, `rm` and `rmi` showed up.

Currently, @allanday is working on extending and improving the Toolbox documentation as part of the bigger Silverblue effort, and we're very likely going to be rethinking some aspects of the Toolbox command line interface. So I am a little hesitant at the moment to make bigger changes because things are going to change anyway in the near future.

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal , and the Go version supports:
```
$ toolbox create foo
...
$ toolbox enter foo
...
```
