### ISSUE TITLE
Move from registry.fedoraproject.org to quay.io

### ISSUE THREAD

**Issue by sumantro93** [containers/toolbox#1346]
I met Michal from CPE at Flock '23 and CPE is planning to move things from reg.fp.o to quay.io 
This means we will now be pulling fedora images from a different place. 
I am creating this place holder issue, to track and work on it when the move happens.

**Comment by debarshiray** [comment]
The [latest](https://pagure.io/fedora-infrastructure/issue/11543) consensus is evolving towards continuing to use `registry.fedoraproject.org` in clients in the short to medium term, and putting in place a server-side redirection to `quay.io`.  This would make it easier to revert the migration if things go wrong or if we need to do another migration relatively soon.

Given that, I am going to close this issue so that the issue tracker represents the list of items that we want to work in the short to medium term.

Regardless, thanks for staying on top of this, @sumantro93 !
