### ISSUE TITLE
fedora-toolbox image doesn't have cracklib-dicts

### ISSUE THREAD

**Issue by ibotty** [containers/toolbox#1351]
**Describe the bug**
A clear and concise description of *what the bug is*. If possible, re-run the command(s) with `--log-level debug` and put the output here.

**Steps how to reproduce the behaviour**

```
> pwmake 64
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Error: Password generation failed - required entropy too low for settings
```

**Expected behaviour**
```
> pwmake 64
N3j=uD!ipDAMf
```

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.4`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.4-1.fc38.x86_64`

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.20.6
Built:        Fri Jul 21 14:23:26 2023
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-4.6.0-1.fc38.x86_64`

**Info about your OS**
Fedora Silverblue 38

**Comment by debarshiray** [comment]
> ```
> > pwmake 64
> /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
> /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
> /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
> Error: Password generation failed - required entropy too low for settings
> ```

The message *required entropy too low* is misleading.

The actual problem is the absence of the [CrackLib](https://github.com/cracklib/cracklib) dictionaries (on Fedora that's the `cracklib-dicts` RPM).  Those *No such file or directory* messages are coming from `PWOpen()` inside CrackLib.  It tries to open the missing dictionary, fails, calls `perror(3)` with `errno(3)` set to `ENOENT`, and that prints *No such file or directory*.

Now the question is, why are the CrackLib dictionaries missing?  We could also try to improve the error handling in [libpwquality](https://github.com/libpwquality/libpwquality/).

**Comment by debarshiray** [comment]
Here's a pull request to improve the error handling in libpwquality:
https://github.com/libpwquality/libpwquality/pull/85

**Comment by debarshiray** [comment]
Renaming the issue to highlight the problem closer to Toolbx's sphere of influence.  ie., the `fedora-toolbox` image doesn't have the `cracklib-dicts` RPM.

**Comment by debarshiray** [comment]
Turns out that the `fedora-toolbox` images for Fedora >= 39 already have `cracklib-dicts`.  Only the one for Fedora 38 didn't have it.  I have now fixed that:
https://github.com/containers/toolbox/pull/1444
https://bodhi.fedoraproject.org/updates/FEDORA-CONTAINER-2024-7eb1f9483f

**Comment by debarshiray** [comment]
Thanks for your feedback!
