### ISSUE TITLE
rpm repo for other distros than fedora silverblue?

### ISSUE THREAD

**Issue by mailinglists35** [containers/toolbox#1364]
website says "Installation [...] On other operating systems it’s just a matter of installing the toolbox package."

there is no `toolbox` package in EL9

````
$dnf list available toolbox
Last metadata expiration check: 0:04:12 ago on Fri 15 Sep 2023 02:39:44 PM EEST.
Error: No matching Packages to list
````

**Comment by debarshiray** [comment]
> there is no toolbox package in EL9

There has always been a `toolbox` package for CentOS Stream 9 and Red Hat Enterprise Linux 9.  eg., see https://gitlab.com/redhat/centos-stream/rpms/toolbox

What do you mean by EL9?

Regardless, it's difficult for an upstream project to have an exhaustive list of downstreams that distribute it.  There are simply too many.  A dedicated page like [Flathub's](https://flathub.org/setup) seems overkill because it's literally one package that needs to be installed.

The *on other operating systems* text isn't meant to be a binding contract.  That's why there are instructions on how to build Toolbx from source.

Does this make sense?  Or did I misunderstand something?

**Comment by debarshiray** [comment]
I am going to close this one because I don't think there's much to be done here.

Thanks for trying out Toolbx, @mailinglists35 !
