### ISSUE TITLE
What is this project's name?

### ISSUE THREAD

**Issue by pmaddams** [containers/toolbox#1399]
Is it Toolbox or Toolbx? Please don't tell me the O is silent. The [project website](https://containertoolbx.org/) uses both. If I search for software that uses Toolbo?x, should I search for both spellings? Please provide an FAQ.

**Comment by debarshiray** [comment]
> I suggest that you change the name back to Toolbox, 

That's unlikely to happen.  :)

The decision to drop one *o* and rename the project as *Toolbx* happened in October 2021: https://github.com/containers/containertoolbx.org/pull/1

Renaming a live project with many different pieces is a deceptively large amount of work, which is why we never got around to getting it fully done.

> because Toolbx is unpronounceable.

The pronunciation is still *toolbox*, but it's spelt without the final *o*.  It's similar to how Flatpak is flatpack without the *c*.

The problem with spelling the name as Toolbox is that it's a very generic word.  More
and more people have been pointing out that "toolbox" is terribly difficult to search for, and it's impossible to find any decent Internet real estate by that name.

> Imagine people at a conference talking about container tools. I think they will pronounce it Toolbox, so it's confusing for the name to be spelled different. It's not too late to change it back.

Most people will likely have seen the slides at conference talks and blogs referring to the project as Toolbx, and they will probably use tab completion when using the actual command.  Those should reduce the confusion a bit.

> Do you want help changing the name in various places?

You could help finishing the rename to Toolbx.  :)

**Comment by debarshiray** [comment]
Pull requests for:
* the code: https://github.com/containers/toolbox/pull/1446
* the website: https://github.com/containers/containertoolbx.org/pull/39

... to advance with the renaming some more.

**Comment by debarshiray** [comment]
> > Do you want help changing the name in various places?
> 
> You could help finish the rename to _Toolbx_. :)

The above commits and pull requests contain pointers to work that's left to be done.  I think the easiest next step would be to add create a `/run/.toolbxenv` stamp file and migrate our own use of the stamp file to the new name.

**Comment by debarshiray** [comment]
Closing.  Thanks for stopping by.
