### ISSUE TITLE
Fish Shell Completions

### ISSUE THREAD

**Issue by er2** [containers/toolbox#1516]
Toolbox would be much more enjoyable to use with shell auto-completions.

It's much easier to hit tab with

```
toolbox create --distro ␉
```
and get available distros than to get an error and have to pull up docs.

I picked ubuntu since debian wasn't available. Then I needed a release. It would have been friendlier to suggest the latest LTS and ask me to confirm, BTW.

The syntax for release isn't obvious. I expected `--release` to take a nickname like jammy. Autocompletion would make this a non-issue.

**Comment by debarshiray** [comment]
Toolbx has been shipping completions for fish since 0.0.99.4.

They do auto-complete `--distro` with the names of officially supported distributions, but not `--release` though.  Although, the error does give a hint:
```
$ toolbox create --distro ubuntu --release jammy
Error: invalid argument for '--release'
The release must be in the 'YY.MM' format.
Run 'toolbox --help' for usage.
```

Do you know of a good way to map the alliterative code names of Ubuntu's releases to their month and year version numbers?

**Comment by debarshiray** [comment]
I tested with a fresh Fedora Workstation 40 virtual machine and the fish completions do work.

I am going to tentatively close this.  Please leave a comment or open a new issue if you think I got it wrong.

Thanks for stopping by!  :)

**Comment by er2** [comment]
That's fine. I think it's an issue with the Arch package

**Comment by debarshiray** [comment]
> That's fine. I think it's an issue with the Arch package

I see.  Thanks for the confirmation!
