### ISSUE TITLE
Fedora 39 Image doesn't build

### ISSUE THREAD

**Issue by KilianHanich** [containers/toolbox#1520]
**Describe the bug**
The Fedora 39 image of this repository (images/fedora/f39) doesn't build anymore.

**Steps how to reproduce the behaviour**
1. Go to the repository
2. Type in 'podman build images/fedora/f39'
3. See error 'STEP 20/21: (...)'

**Expected behaviour**
No error.

**Actual Behaviour**
The following error:
```
STEP 20/21: RUN broken_packages="$(rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n"   | sed --quiet --regexp-extended '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }'   | uniq   | sort)";   if [ "$broken_packages" != "" ]; then     echo "Packages with missing files:" >&2;     echo "$broken_packages" >&2;     false;   fi
Packages with missing files:
python3-dnf
Error: building at STEP "RUN broken_packages="$(rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n"   | sed --quiet --regexp-extended '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }'   | uniq   | sort)";   if [ "$broken_packages" != "" ]; then     echo "Packages with missing files:" >&2;     echo "$broken_packages" >&2;     false;   fi": while running runtime: exit status 1
```

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.5`

**Toolbx package info (`rpm -q toolbox`)**
`toolbox-0.0.99.5-11.fc40.x86_64`

**Output of `podman --version`**
`podman version 5.1.1`

**Output of `podman version`**
```
Client:       Podman Engine
Version:      5.1.1
API Version:  5.1.1
Go Version:   go1.22.3
Built:        Tue Jun  4 02:00:00 2024
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-5.1.1-1.fc40.x86_64`

**Info about your OS**
Fedora Kinoite 40

**Additional Context**
Podman was called from outside a container.

**Comment by debarshiray** [comment]
Thanks for the heads-up!

> ```
> STEP 20/21: RUN broken_packages="$(rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n"   | sed --quiet --regexp-extended '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }'   | uniq   | sort)";   if [ "$broken_packages" != "" ]; then     echo "Packages with missing files:" >&2;     echo "$broken_packages" >&2;     false;   fi
> Packages with missing files:
> python3-dnf
> Error: building at STEP "RUN broken_packages="$(rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n"   | sed --quiet --regexp-extended '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }'   | uniq   | sort)";   if [ "$broken_packages" != "" ]; then     echo "Packages with missing files:" >&2;     echo "$broken_packages" >&2;     false;   fi": while running runtime: exit status 1
> ```

This means that the listed packages had some of their files stripped out by the base `fedora` image, and they need to be restored through the `missing-docs` file.

It looks like something changed since then and it builds again now.

Anyway, the `fedora-toolbox:39` image is no longer defined as Containerfile:s, but as a Kickstart:
https://fedoraproject.org/wiki/Changes/ToolbxReleaseBlocker
https://pagure.io/fedora-kickstarts/

... and the `fedora-toolbox:40` and newer images are defined as KIWI descriptions:
https://fedoraproject.org/wiki/Changes/KiwiBuiltCloudImages
https://pagure.io/fedora-kiwi-descriptions

We ignored the Kickstart for the purposes for this GitHub project and stuck to Containerfiles, because it was short lived and it's difficult to build them outside the Fedora infrastructure.  https://github.com/containers/toolbox/pull/1563 is somewhat related.
