### ISSUE TITLE
Security Feature: Better $HOME directory separation

### ISSUE THREAD

**Issue by zem** [containers/toolbox#320]
Security Feature Request:

After looking at Toolbox for a while I am afraid  to say:  
**Toolbox does not separate the data that has to be separated to actually improve security!** 

For example:  

- I need  ~/.gnupg being inaccessable from the container running my firefox instance. 
- I need $CONFIDENT_DATA also being seperated from Firefox
- I need more than one Firefox instance running. 

My proposal is to link $HOME/tbox/$CONTAINERNAME as the users home into the toolbox. 

A "send file to container" directory and a "receive data from container" directory would probably be a nice thing, too, but is much harder to implement.

**Comment by evelineraine** [comment]
Hi,

The idea behind toolbox is to provide an easy access to a mutable development environment in which you can install any version of any development tool you want without messing with OS's packages. Initially, it was created for Silverblue, where you couldn't `dnf install` or `pip install`, since `/usr` was immutable. 

Security is not the goal, quite the opposite - commands are expected to run in toolbox container with the same level of privilege, not restricting you, as you work inside the container. 

If what you need is to run a sandboxed process (like a build script for your app), you should create a normal podman container, and bind mount only the required directories inside.

**Comment by debarshiray** [comment]
Yes, as @evelineraine said.

If you want to run graphical applications securely, then I'd suggest looking at [Flatpak](https://flatpak.org/). [Here](https://firefox-flatpak.mojefedora.cz/) is one way to install a Firefox Flatpak.

That said, this feature has been requested in the past too. eg., https://github.com/containers/toolbox/issues/183

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/183

**Comment by markstos** [comment]
> Security is not the goal, quite the opposite - commands are expected to run in toolbox container with the same level of privilege, not restricting you, as you work inside the container.
> 
> If what you need is to run a sandboxed process (like a build script for your app), you should create a normal podman container, and bind mount only the required directories inside.

It would be helpful if a "security is not a goal" statement were added to the README, which is currently silent on Toolbox's intentional lack of security concern.

A malicious container could easily add a malicious `sudo` binary to `~/.local/bin` (or replace any other system binary by using that directory), which could later get executed in the context of the host, leading to full root access on the host.

I'm surprised that Red Hat promotes this approach for their own developers. With open source contributors all over the world and a complex web of software projects, the odds of something or someone in the dependency chain getting compromised seem reasonably probable to happen over time.

**Comment by debarshiray** [comment]
> > Security is not the goal, quite the opposite - commands are expected to run in toolbox container with the same level of privilege, not restricting you, as you work inside the container.
> > If what you need is to run a sandboxed process (like a build script for your app), you should create a normal podman container, and bind mount only the required directories inside.
> 
> It would be helpful if a "security is not a goal" statement were added to the README, which is currently silent on Toolbox's intentional lack of security concern.

This was addressed in https://github.com/containers/toolbox/issues/1020

> A malicious container could easily add a malicious `sudo` binary to `~/.local/bin` (or replace any other system binary by using that directory), which could later get executed in the context of the host, leading to full root access on the host.

How is that different from someone, knowledgeable or otherwise, following malicious instructions from somewhere?  Is it because somewhere hidden in the implementation there is a container?  Would it be acceptable if there was no container?

> I'm surprised that Red Hat promotes this approach for their own developers. With open source contributors all over the world and a complex web of software projects, the odds of something or someone in the dependency chain getting compromised seem reasonably probable to happen over time.

And?

**Comment by markstos** [comment]
> And?

And exactly this problem recently happened, with Red Hat NPM modules harvesting secrets from home directories:

https://www.stepsecurity.io/blog/multiple-redhat-cloud-services-npm-packages-compromised

So if the concerns with the toolbox security model seemed theoretical before, they are not now.

**Comment by debarshiray** [comment]
> > And?
> 
> And exactly this problem recently happened, with Red Hat NPM modules harvesting secrets from home directories:
> 
> https://www.stepsecurity.io/blog/multiple-redhat-cloud-services-npm-packages-compromised
> 
> So if the concerns with the toolbox security model seemed theoretical before, they are not now.

And what makes you demand that it's Toolbx's responsibility to protect you from this?  Did you file similar complaints about your CLI shell and terminal emulator's security model?  What about the security model of GNU Coreutils?
