### ISSUE TITLE
toolbox reset errors with failed to set GID mapping of user namespace

### ISSUE THREAD

**Issue by mangonel** [containers/toolbox#329]
toolbox reset
toolbox: failed to set GID mapping of user namespace

user_gid_real=$(id -rg 2>&3)

Works when I change
`if ! newgidmap "$unshare_pid" 0 "$user_id_real" 1 1 "$userns_gid_start" "$userns_gid_len" 2>&3; then` 
to
`if ! newgidmap "$unshare_pid" 0 "$user_gid_real" 1 1 "$userns_gid_start" "$userns_gid_len" 2>&3; then`

**Comment by debarshiray** [comment]
I have come across this `failed to set GID mapping of user namespace` error once or twice myself. It always felt like a race somewhere because re-running `toolbox reset` would make it go away, but it was always the GID mapping that failed, not the UID mapping right below it.

If I understood correctly, you separately read the GID and used it when setting the mapping, right?

Is your `id -rg` different from your `id -ru`? Does it reliably fail for you, or does it fail only once in a while?

It would indeed be more correct to explicitly use the GID, but I am curious why it fails once in a while when the UID is the same as the GID.

Good news is that we can drop the entire `toolbox reset` code and switch to `podman system reset` once Podman 1.7.0 is out.

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal The Go version deprecates the `reset` command in favour of `podman system migrate` and is now merely a wrapper around it.
