### ISSUE TITLE
Unable to connect to /tmp/.X11-unix/X1 from toolbox

### ISSUE THREAD

**Issue by lokedhs** [containers/toolbox#347]
I am using Fedora Silverblue, with Xorg enabled (i.e. no Wayland).

I'm attempting to load McCLIM, which is a Common Lisp-based user interface. It does not link with Xlib, but instead uses CLX which is an implementation of the X11 protocol, written in Common Lisp. When I attempt to start a program using McCLIM, I get a `connection refused` error when attempting to connect to the Unix socket `/tmp/.X11-unix/X1`.

When looking in this directory, I can indeed confirm that this socket cannot be found there.

However, I note that other X11 applications such as xclock runs fine. To debug this, I ran `strace xclock` to figure out what it does, and in that trace I can see that it performs a `connect` to `/tmp/.X11-unix/X1`, which succeeds.

I'm suspecting that there is something special going on when xclock is run, which does not happen when McCLIM attempts to connect to the same socket.

It seems reasonable to guess that this special thing is implemented on the Xlib side (since McCLIM doesn't use Xlib). I'm a developer of McCLIM, so if there is something special implemented by Xlib, I can make the appropriate changes to it, but right now I'm at a loss as to what is happening.

**Comment by debarshiray** [comment]
The X.org server listens on two different sockets:
1. An abstract UNIX socket with an address that has the prefix `@/tmp/.x11-unix`
2. A UNIX socket on the file system located at `/tmp/.x11-unix`.

The abstract socket doesn't work if you have a network namespace, and in that case you need to use the socket on the file system. This is what Flatpak does because it creates containers with a network namespace.

Toolbox containers don't have a network namespace (because `podman create --net host`), so applications can talk to the X.org server via the abstract socket and hence it doesn't make `/tmp/.x11-unix` available inside the container.

My guess is that CLX doesn't know about the abstract socket.

Thanks for stopping by.

**Comment by debarshiray** [comment]
I am tentatively closing this. Feel free to leave a comment if you are still stuck.

**Comment by lokedhs** [comment]
Thank you. The analysis seems correct, and I'm looking into providing the necessary changes to CLX for this to work.

I would neve rhave figured this out without your help.

**Comment by debarshiray** [comment]
I am glad it helped. Good luck!
