### ISSUE TITLE
Adjust home path

### ISSUE THREAD

**Issue by ckaspro** [containers/toolbox#348]
I like to use several toolboxes, with different content. To properly distinguish these, I'd like to mount them in subdirectories (e.g. container1:/home/user -> host:/var/home/user/container1). It's a similar thing to #183 , but not as security- centric.
Is there a way to achieve this at the moment / via consistent workaround (I don't want to change a line of code and after the next update I'm saving files somewhere else ;)  )?

Update: I wouldn't actually mind (maybe even appreciate) having these under different user-contexts - but in the same general directory. That way there is a clear distinction and separation.
For presenting this to the end- user in a "nice way", one could add an extra link opening the file-browser as sudo... (just thinking loud here)

Thanks in advance,
Chris

**Comment by yilkalargaw** [comment]
I usually just do ```HOME=/home/user1/container1``` before creating the containers and just alias use an alias to open them. (```alias toolbox1='HOME=/home/user1/container1/toolbox "$@"'```)

**Comment by debarshiray** [comment]
Yeah, overriding `$HOME` is one way to do it.

**Comment by JaneSmith** [comment]
I'd also like to see something like this. My main use case for Toolbox is to set up throwaway development environments, for either working on projects, or just quickly compiling some software from source. I don't want to pollute my system with random files from dependencies, etc. just to compile something once. Toolbox seemed perfect for this, as it claims to provide an isolated container to keep the host clean.

This didn't turn out to work quite how I expected though. While Toolbox *does* keep the host OS clean, it doesn't keep the home directory clean at all. That still gets totally polluted. For example, using a throwaway container to build something that uses `rust`, my home directory ended up getting altered in several ways:

* A `~/.cargo` directory was silently created, containing many Rust-related binaries, source packages, etc. for a total of 123 MB.
* A `~/.rustup` directory was silently created, containing many more Rust-related binaries, for a total of 683 MB.
* My `~/.bash_profile` file was silently altered to add the `~/.cargo/bin` directory to my $PATH ahead of everything else.
* My `~/.profile` file was silently altered to add the `~/.cargo/bin` directory to my $PATH ahead of everything else.
* Who knows what else.

Yikes. I realise now from the comments above that I can override the $HOME environment variable manually to try to work around this, but this was not intuitive or expected to me. Since Toolbox is supposed to be (or at least as I understand it) a simplified and user-friendly way to get into containers, I would appreciate if this could be handled in some better way.

My opinion is that a Toolbox should probably have its own unique user and home directory by default. But if this is too complicated to implement, then perhaps there could at least be a `-h` or `--home` argument when creating a new toolbox, to set its default $HOME? So that when you enter the toolbox in future, it would get that $HOME value set automatically. For example, something along the lines of `toolbox create -c temp-myproject -h ~/Toolboxes/temp-myproject`.

**Comment by HarryMichal** [comment]
This sounds very reasonable to me. What do you think @debarshiray??

**Comment by ckaspro** [comment]
I support this @JaneSmith , all I need - nicely put!

**Comment by yilkalargaw** [comment]
I second the idea too. But until it gets implemented you could use [direnv](https://github.com/direnv/direnv). It is a handy tool that allows to specify environment variables on a directory basis. You can use the following work flow

```
- install direnv and hook it to your shell
- create a temporary directory eg. ~/somedev
- add a .envrc file with the environment variables you want (in this case HOME=/home/user/somedev
```
now every time you go into the somedev directory it will assume it is the home directory and resets when you step out of it . You could do all the steps in one command like:

``` bash
mkdir ~/somedev && echo export HOME=/home/user/somedev > ~/somedev/.envrc
````
I currently use a similar work flow.

**Comment by rugk** [comment]
I agree there should at least be an option to not mount the home dir (ref https://github.com/containers/toolbox/issues/183#issuecomment-623103780). Actually, I would even be fine if it uses – similar to flatpak – some dir in `~/.var/app`, maybe better `~/.var/toolbox` or so, where all files in the home dir are saved by default.
I quite like that flatpak model, because you have all the data from one container in one place, and if you delete the container, you can also delete all app data. (or just measure the space your new "I've tried out rust" project took), e.g. (as it's done in gnome-control-center)

Then, for convenience, it should possibly always mount in the current $PWD, if you start it from a project folder, you likely expect to have the files in there. Just, your `~/rust-project` folder, does not need any access to `~/Pictures/private/…` etc.

Anyway, of course one should be able to optionally mount home as read-only or even writable, but I don't think that is really needed for most applications.
And one should be able to not mount the current `$PWD`.

So you'd have a "middle-ground" here as a new default.

**Comment by markstos** [comment]
[tlbx](https://gitlab.com/uppercat/tlbx) fork has a `-n` option to not bind-mount the home directory.

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/183

**Comment by rugk** [comment]
Noooo… you can still have other use cases/reasons for having a different $HOME then an "Isolated development environments to fend against bugs and malware in code under development"…

IMHO, this is still a feature that toolbox should have.

**Comment by JaneSmith** [comment]
I don't understand why this issue was closed. It's not a duplicate of that. This isn't just about security. I really hope this will be reconsidered as I love Fedora Silverblue and love that it has a built-in tool to set up pet containers, but it doesn't really do the job currently. I don't want to have to use a fork just for that... I use toolbox for pet containers to deal with various programming projects, and I don't want my home directory to be cluttered by the containers. It has nothing to do with security.

**Comment by markstos** [comment]
@JaneSmith why not use a fork if it has the features you need?

**Comment by JaneSmith** [comment]
I'd prefer to use Toolbox rather than a fork, because Toolbox is better supported with more developers, and is included with Fedora out of the box. When I'm moving from machine to machine, Toolbox is already there, without me having to install forks. In my humble opinion, this feature request is for something that should be core, basic functionality, as not having it kind of defeats the purpose of Toolbox. I don't see it as a really "out there" unusual special feature. I'm therefore voicing my support for it and hoping that it will be implemented for this project.

**Comment by markstos** [comment]
@JaneSmith I agree on all points. I expect the feature will be implemented the first time the current insecure design is publicized to play a part in a security breach, if not sooner.

**Comment by markstos** [comment]
The first sentence in the docs says it runs _fully unprivileged _. Sounds secure, huh?

Also in the main description: _The intention of these systems is to discourage installation of software on the host, and instead install software as (or in) containers._ Also sounds like this project must add significant security.

Nowhere do the docs highlight that it's sharing every document your user owns with with every container, including SSH keys and files unrelated to what's happening in the container.

The current situation is not only insecure, but misleads to convey that using containers like this provides significant security, when it's hardly the case the containers can access all your files!

If you search for "home" in the README, there is no documentation that your home directory is shared in this way.

**Comment by yilkalargaw** [comment]
@markstos you actually voiced what I was feeling. Folks think that security just implies not having no access to root but most of the time it might just be sufficient to compromise a user directory. Especially in a desktop setting.

It is really bad idea to make toolboxes sound like a secure area you could experiment in by installing software and running binaries while not giving an opportunity to opt out of sharing you user directory. I use [tlbx](https://gitlab.com/uppercat/tlbx) and my own crappy scripts for such purposes. When using toolboxes I usually change $HOME even though that means podman will stall and I have to restart any process associated with podman, toolboxes and fuse-overlay systems.

I think it is very necessary to think of this issue as a security issue and patch it now instead of waiting for the golang rewrite.

**Comment by ChrisTucker2000** [comment]
I want this too. A middle ground (home accessible, but not defined as HOME), and a more untrusted mode (home not accessible at all).

> I usually just do `HOME=/home/user1/container1` before creating the containers and just use an alias to open them. (`alias toolbox1='HOME=/home/user1/container1/toolbox "$@"'`)

If a middle ground solution is this simple... then why can't it be implemented into Toolbox as an option? Just take the home path as an argument when creating the toolbox and save it somewhere, probably the same way as how the container name is saved. Then read that path and set it when entering the container...

**Comment by swick** [comment]
To make things a bit more concrete:

* `--new-home` which would tell toolbox enter to not mount host $HOME (or mount it somewhere else in the container which is not $HOME)
* `--from-home path1:path2:pathN` which would tell toolbox enter to mount specific paths from host $HOME to the container home

So for example if I have source directories in ~/Projects, need to sign things with gpg and need ssh to connect to a server and my git config I could create a toolbox like this:

`toolbox create --new-home --from-home Projects:.ssh:.gnupg:.gitconfig`

So is this something would be accepted upstream? I would even work on this if the plan makes sense.

**Comment by JaneSmith** [comment]
Is there any update on this issue? It looks like onuruluag has implemented it separately back in April, as referenced above. Could those changes be pulled into Toolbox proper?

**Comment by xrishox** [comment]
i would like to see support added for this. not only do i not want my toolboxes polluting my home dir, sometimes i want different toolboxes to have configurations that would conflict with eachother. i also want my toolboxes to be entirely portable. i want to be able to export the image from 1 machine, import them into another machine and keep all of my configuration i've done. on top of that being able to fully back up these environments would be really nice too. that said i do like having access to my native home directory structure from inside the toolbox. i don't want my native home to not be mounted at all, i just don't want it to be the home inside of the toolbox. having functionality to support this would be absolutely awesome.

**Comment by debarshiray** [comment]
>  use toolbox for pet containers to deal with various
> programming projects, and I don't want my home
> directory to be cluttered by the containers.

Maybe use `/opt` or something for your projects?

**Comment by swick** [comment]
The problem isn't the source code but all the build and runtime tools which have state somewhere in $HOME.

**Comment by debarshiray** [comment]
> The problem isn't the source code but all the build and runtime tools
> which have state somewhere in $HOME.

Can't those be redirected by overriding some default configuration for those toolchains somewhere? Just curious.

**Comment by swick** [comment]
Some do, some don't, sometimes they are used by other tools which don't let you pass the necessary config. Either way it requires much better knowledge of the tools you're using, more complexity you have to deal with and that makes it a lot more error prone. I understand the reluctance to add this feature but I don't really see another way to get a somewhat decent UX.

**Comment by HunterGraubard** [comment]
I desperately want this feature. This issue has been here for two years now and there's obviously still a lot of support for it. Can I ask why this issue is marked as Closed instead of Open? It was originally marked as Closed on the 18th of May, 2020, as a "duplicate" of #183. However, as has since been pointed out, _they're separate issues_:

- Issue #183 is asking for the container to be isolated with no access to the home directory. This means the user's home directory is not mounted at all, for security reasons.
- This issue #348 is asking for the container to have an adjustable home directory, possibly as a subdirectory within the user's normal home directory. This means the user's home directory is still mounted. This is not about security, but rather file organisation and "directing" processes within the toolbox towards a certain folder.

They're two separate issues, so it seems to me that it was invalid to Close it originally as a duplicate. Given the amount of discussion since then, the repeated requests for the feature, people even forking to try to implement it... **Could this issue be Opened?**

***

Earlier today I read a blog post from Christian F.K. Schaller, about [Fedora's vision for the Linux Desktop](https://blogs.gnome.org/uraeus/2021/09/24/fedora-workstation-our-vision-for-linux-desktop/). It talks about all the main modern innovations, such as OSTree, Flatpak, Silverblue, PipeWire, Wayland — and also Toolbox.

The article claims that using Toolbox for containers improves over traditional development by reducing cross-contamination between projects, as you can have one container for each project. Here's a direct quote:

> In fact pet containers even improves on how we used to do things as they allow you to very easily maintain different environments for different projects. So for instance if you have two projects, hosted in two separate pet containers, where the two project depends on two different versions of python, then containers make that simple as it ensures that there is no risk of one of your projects ‘contaminating’ the others with its dependencies

They literally say "ensures that there is no risk". But this is objectively false, because of this specific issue. Sure, you can have separate containers... but if they're sharing the same home directory, there is indeed still cross-contamination. Look at what another person posted earlier in this discussion thread, about how building something that uses Rust polluted the home directory with 800+ MB of stuff. Is this not completely contradictory to the above quote? Now both containers are contaminated with others' dependencies.

The article concludes by saying that their vision is for these things to become more mainstream, and they want developers to embrace the pet container model. Well, I would love to embrace the pet container model! Absolutely... But this issue is the main thing holding me back from doing so. In fact, specifically because of _this one issue_, I spin up entire virtual machines as my "pet containers" instead. This is because I do not want my containers to have cross-contamination, and I do want my normal home directory to be polluted by all sorts of random development junk.

***

Please seriously consider this feature. I'm not a developer, but to me it seems like something incredibly simple to implement and maintain. It doesn't seem like a highly complex feature that needs thousands of lines of code and constant maintenance to keep working. It's a simple thing that would have an enormous impact on this software can be used.

**Comment by yilkalargaw** [comment]
I think it has grown into a contention point and I have given up on it being implemented. 

Before I go on more detail I want say that was and still kind of am a fan of this project and I understand how hard it is to maintain an opensource project in which people request features without suggesting ways of implementing it or without having to deal with test cases and build failures. But I am going to point out my opinions on this topic for the last time. I also want it to be known that all criticisms arise from my love of the idea behind the project because it think it is exceptionally brilliant one.

1. The feature is necessary if a wider array of to embrace pet containers. People have different work flows and they are going to hit this problem at one time or another. They have to deal with things that can't be installed using dnf like programming language package managers like cargo, programming language version managers like rbenv, rvm , nvm and the like. They might also have to work with programs like direnv which use hooks into .bashrc and .bash_profile to work properly. And many of these things can be dealt with if you can selectively share the home directory.

2. It also cleaner to sometimes have legacy projects you are working on to not litter things in the home directory.

3. It is also better for security reasons. I am not saying this is a cure to solving security problems with pet containers but I think it is one of the reasons people seek isolation through containers.

4. I have tried and suggested several hacks to achieve a similar thing but always ran into the wall because podman or fuse for some reason don't like it when give them alternate home directories through environment variables and they keep failing because they don't behave like regular bash scripts and crash in this edge case.

5.  I have tried to read the toolbox source code but it has grown way more complicated than it needed to be. The go rewrite has made it harder for people to contribute if they do not know podman at an api level. I don't understand the necessity for rewriting using golang because CPU bottleneck or IO bottleneck  has never been an issue with this program. People at the max run it several times a minute.

6.  And lastly the maintainers have always disregarded the necessity of the feature. It might not be the actual reason but I think they have taken it as some kind of critique against the idea of their whole project or something which it is not. The number of people who run into this issue keeps amazing me.


Because of all the above issues I was not able to keep using toolbox. But I still stuck with the wonderful idea behind it all the idea of pet containers using podman. People have written several  alternatives from simple ones that just manipulate command line arguments to podman to more complicated api level implementations.  I am going to list out a few incase people running to this issue might find alternatives.

1. [tlbx](https://gitlab.com/upperca/tlbx): a simpler bash alternative that uses default oci containers to run any distro but you can only use fedora, centos or redhat as the host.
2. [distrobox](https://github.com/89luca89/distrobox): more complete implementation and works on any distro, implemented using posix shell.
3. [podenv](https://github.com/podenv/podenv): built around the idea of container apps but can do what you need.
4. [nsbox](https://github.com/refi64/nsbox): heard a lot of good things about it but have not used it but it looks really good. Has a whole [documentation site](https://nsbox.dev/)
5. [etui](https://gitlab.com/bkhl/etui): I have not worked with it much but has good ideas behind it.

ps. there might be others I don't know about so we might share them to compare implementations and incase they might be helpful to people facing similar issues.

**Comment by markstos** [comment]
@yilkalargaw There's a typo in the `tlbx` link above. It should be: https://gitlab.com/uppercat/tlbx

**Comment by yilkalargaw** [comment]
Thanks @markstos I think I have corrected it.

**Comment by maxboone** [comment]
@yilkalargaw thank you for the write-up, couldn't agree more. 

I do work for multiple teams inside our business, and every team / project that I need to run and test has it's own little quirks or patches. I used to run Windows Subsystem for Linux, and it was nice that you could just run completely separate (actually Hyper-V containerized) environments side-by-side.

I installed Fedora in the hopes that I could use toolbox in a similar way; Unfortunately the home-directory is shared by default indeed. I guess this can probably be overcome with some scripting here and there and/or using a non-default image. I will instead look into the alternatives you list.

**Comment by maxboone** [comment]
I think the hard part in this issue is that OCI-containers are created immutably. One of the main components of `toolbox` is that it has both a host-running management application and a special entrypoint that starts up the container configured properly and up-to-date according to the host set-up.

However, the home-directory is not mounted using this entrypoint. Instead, when `toolbox create` is run, the host-application checks which home-directories it should pass to the container and creates the mounts for these directories in the OCI-container (immutable) definition.

As far as I can tell there are two ways to go here (user = `bark`, container = `yard`):

1. Do not create direct mounts for the home directory when creating the container; Instead, mount the necessary home-directories of the users in `/run/host/home/bark`, have `initContainer.go` create directories on the image & symlink them on boot of the container (similar to existing approach for other exposed files).

2. Upon creation of a container, allow a flag (e.g. `--private`) that creates the `yard::/home/bark` mount but mounts it on the host to a configured directory (default `host::/home/bark/.toolbox/home/yard/bark/...`)

Considering security - as the toolbox runs under the same uid & gid as the host user, I wouldn't see leaving out a mount as secure. I also wouldn't go as far as allowing fully "private" containers, you can just as well use podman / docker / nerdctl without this. I also prefer option 1, as this keeps the door open to later mount the home directory (or even another directory) _anyways_.

**Comment by rugk** [comment]
@maxboone What is this `/run/.containerenv` file? It does not exist in my Fedora Silverblue 35 installation? (also not in a container)

**Comment by maxboone** [comment]
> @maxboone What is this `/run/.containerenv` file? It does not exist in my Fedora Silverblue 35 installation? (also not in a container)

It should be created by the init script / entrypoint of the container:

https://github.com/containers/toolbox/blob/7351313dc89680164e0ccf56f7de97832fcd63c7/src/cmd/initContainer.go#L145

**Comment by rylancates** [comment]
After reading this, I firmly believe LXD is what the majority of people on this issue are looking for. LXD is great for pet containers. I’ve recently moved to Fedora for the vanilla Gnome desktop experience since Pop!_OS is taking a different direction than I like and was exploring Fedora’s container virtualization story.

The issue for me, like others, with toolbox has nothing to do with security necessarily and everything to do with functional separation of concerns.

For example: when developing for node.js, it has a single package cache located in your home directory (somewhere in ~/.npm I believe).

Say you want to use toolbox to run multiple development containers to make it possible to have as many repo copies running at once as you want for active development, PR reviews, and experimental refactoring (it’s hugely convenient to be able to context switch for free or at least very cheap).

If you use `link` in your package.json (monorepos), or even if you don’t: you will run into issues with this workflow with toolbox where when you build your project in one container, the package cache from its build will stomp over every other container’s package cache due to having a shared home directory.

This entirely defeats the purpose of toolbox to begin with IMO (at least the full extent of my use-case for it).

With LXD, you get a full-fledged, isolated OS at your disposal with minimal overhead. You can choose your own networking (bridged, host, etc.) and storage. You can set resource constraints easily. You can export, import, restart, start on host boot, and so on. You can have containers, or you can have VMs. Tons of flexibility.

I’ve found that LXD + VS Code with the Remote SSH extension (each of my dev containers gets their own IP address) works flawlessly and VS Code makes ssh port forwarding a breeze with their handy GUI.

I don’t necessarily care for snaps or the direction Canonical is taking and would love to see toolbox evolve to fix this absolutely show-stopping oversight on an otherwise exciting and promising project.

Until then, back to LXD I go…

**Comment by swick** [comment]
Some more anecdotal evidence that this should be a priority:

Tried to eslint my local changes of gnome-shell. Looked up how to install packages globally with npm, installed eslint es described on the homepage, ran it against the code and it didn't work because it doesn't find some dependencies which are definitely there. Installed eslint without the global flag and it magically works. Obviously it's not isolated from other toolboxes anymore.

**Comment by tazihad** [comment]
Why this issue is closed? 
I installed bunch of program inside toolbox. nvm, pipx, dotnet etc. Just to realize that all of this is corrupting my host home directory. And later found out that I have pip available in my host terminal. Even though pip doesn't come installed in Fedora Kinoite. This is weird. This issue makes the whole toolbox project baseless. 
Every toolbox container should come with separate homepage.

**Comment by pyrotek45** [comment]
how is this not a standard feature. anyone who programs rust with a toolbox is going to have a polluted home folder like i found out mine was after installing rustup in a toolbox. big mistake. this needs to be added asap imho.

**Comment by pyrotek45** [comment]
there's a project similar to this called distrobox and it supports having its own home directories, maybe this project should check out their code.

**Comment by JaneSmith** [comment]
@debarshiray You couldn't at least respond to all the extensive feedback and explain why this isn't planned? :(

**Comment by mikezila** [comment]
Could we at least get some rationale or an alternative solution to this problem rather than just a cowardly silent close? This is a very real shortfall that undermines the entire stated purpose of toolboxes. That there are so many proposed fixes and real examples as to why they're needed and yet we get no response is unacceptable.

**Comment by zihadio** [comment]
while having same home folder is convenient for average desktop user. But it's not ideal for developers. Who likes to try bunch of program to try in separate toolbox. 
So, I don't use toolbox in Fedora Kinoite anymore. I always use [distrobox](https://github.com/89luca89/distrobox). 
You can have separate home in your [choosing](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#create-a-distrobox-with-a-custom-home-directory) location.

**Comment by idkman2021** [comment]
> I think the hard part in this issue is that OCI-containers are created immutably. One of the main components of `toolbox` is that it has both a host-running management application and a special entrypoint that starts up the container configured properly and up-to-date according to the host set-up.
> 
> However, the home-directory is not mounted using this entrypoint. Instead, when `toolbox create` is run, the host-application checks which home-directories it should pass to the container and creates the mounts for these directories in the OCI-container (immutable) definition.
> 
> As far as I can tell there are two ways to go here (user = `bark`, container = `yard`):
> 
>     1. Do not create direct mounts for the home directory when creating the container; Instead, mount the necessary home-directories of the users in `/run/host/home/bark`, have `initContainer.go` create directories on the image & symlink them on boot of the container (similar to existing approach for other exposed files).
> 
>     2. Upon creation of a container, allow a flag (e.g. `--private`) that creates the `yard::/home/bark` mount but mounts it on the host to a configured directory (default `host::/home/bark/.toolbox/home/yard/bark/...`)
> 
> 
> Considering security - as the toolbox runs under the same uid & gid as the host user, I wouldn't see leaving out a mount as secure. I also wouldn't go as far as allowing fully "private" containers, you can just as well use podman / docker / nerdctl without this. I also prefer option 1, as this keeps the door open to later mount the home directory (or even another directory) _anyways_.
> 
> For now, I won't have time to look into contributing to this project before May; I'm using the following lines in my `.bashrc` to have the containers use a subdirectory as their home:
> 
> ```
> # Check if we're running inside a toolbox
> TOOLBOX_NAME=""
> if [ -f "/run/.containerenv" ]; then
> 	TOOLBOX_NAME=$(sed -nr 's/^name="(.*)"$/\1/p' /run/.containerenv)
>         HOME="$HOME/.toolbox/homedir/$TOOLBOX_NAME/$USER"
>         mkdir -p "$HOME"
>         bash
>         exit 0
> fi
> ```

is there any reason not to use this solution though?

**Comment by idkman2021** [comment]
> > I think the hard part in this issue is that OCI-containers are created immutably. One of the main components of `toolbox` is that it has both a host-running management application and a special entrypoint that starts up the container configured properly and up-to-date according to the host set-up.
> > However, the home-directory is not mounted using this entrypoint. Instead, when `toolbox create` is run, the host-application checks which home-directories it should pass to the container and creates the mounts for these directories in the OCI-container (immutable) definition.
> > As far as I can tell there are two ways to go here (user = `bark`, container = `yard`):
> > ```
> > 1. Do not create direct mounts for the home directory when creating the container; Instead, mount the necessary home-directories of the users in `/run/host/home/bark`, have `initContainer.go` create directories on the image & symlink them on boot of the container (similar to existing approach for other exposed files).
> > 
> > 2. Upon creation of a container, allow a flag (e.g. `--private`) that creates the `yard::/home/bark` mount but mounts it on the host to a configured directory (default `host::/home/bark/.toolbox/home/yard/bark/...`)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Considering security - as the toolbox runs under the same uid & gid as the host user, I wouldn't see leaving out a mount as secure. I also wouldn't go as far as allowing fully "private" containers, you can just as well use podman / docker / nerdctl without this. I also prefer option 1, as this keeps the door open to later mount the home directory (or even another directory) _anyways_.
> > For now, I won't have time to look into contributing to this project before May; I'm using the following lines in my `.bashrc` to have the containers use a subdirectory as their home:
> > ```
> > # Check if we're running inside a toolbox
> > TOOLBOX_NAME=""
> > if [ -f "/run/.containerenv" ]; then
> > 	TOOLBOX_NAME=$(sed -nr 's/^name="(.*)"$/\1/p' /run/.containerenv)
> >         HOME="$HOME/.toolbox/homedir/$TOOLBOX_NAME/$USER"
> >         mkdir -p "$HOME"
> >         bash
> >         exit 0
> > fi
> > ```
> 
> is there any reason not to use this solution though? Also what is the correct way of using it, do I add it to the end of .bashrc?

k so it seems to work when you add it just before "unset rc". I also added "cd ~" before "bash" so that it also opens the home folder but idk if it will actually work. It seems to work for me but that could be for some different reason or something because i dont really know what I am doing. Anyway still is there any disadvantage to using that approach?

**Comment by Enteleform** [comment]
@debarshiray

> I am going to close this issue so that the list of open issues doesn't balloon out of control, and continues to roughly reflect the items that are on the current to-do list. However, it will still be around for future reference.

> Not having something on the immediate to-do list isn't the same thing as don't solve it. There's such a thing as priority.

It would be helpful to pick a primary thread (#183, #320, #331, #348, #1044, #1470, #1510) for this issue and reopen it, so that people can be notified when the issue is resolved. #183 and #348 are good candidates, as they have the most activity and dialog surrounding the issue.

It is apparent that this issue is affecting many people, as evidenced by the numerous duplicates of the issue and the extensive ongoing dialog.

Keeping an issue open would:
- signal that the issue is intended to be resolved at some point
- provide a singular notification channel for those who are currently resorting to workarounds or alternative solutions
- mitigate further duplicates from being created

**Comment by debarshiray** [comment]
The primary issue is https://github.com/containers/toolbox/issues/183  Aren't you getting notifications from updates to it?

**Comment by trarer** [comment]
In general Linux, the command to change the HOME path is:

```
# usermod -d /my/new/home -m username
```
However, the premise for this command to be executed effectively is that the user cannot log in. This command can only be executed by using this user to log in to this container. This is a dead loop. Currently, toolbx does not seem to provide a way for other users to log in.

**Comment by gattolfo98** [comment]
I'm surprised that is not a base feature of toolbox, i think adding this can help al lot of people that want to maintain their home clear.

**Comment by DUB1401** [comment]
It's really a very strange inexplicable reluctance to do basic things. Is there any hope that you can accept a high-quality Pull Request, if there is one?

**Comment by gattolfo98** [comment]
> It's really a very strange inexplicable reluctance to do basic things. Is there any hope that you can accept a high-quality Pull Request, if there is one?

There is more than one issue about this and apparently there is a not a insignificant number of people interested in this feature, but the issues are closed (Not planned) so i don't know if is because there is a technical reason or they have other things more important or just they don't want to implement that.

**Comment by debarshiray** [comment]
> Duplicate of [#183](https://github.com/containers/toolbox/issues/183)

https://github.com/containers/toolbox/issues/1044 is more appropriate.

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/1044

**Comment by debarshiray** [comment]
> Yeah, overriding `$HOME` is one way to do it.

It turned out that this was a regression in the Go implementation.  See https://github.com/containers/toolbox/issues/1564
