### ISSUE TITLE
support for non-Fedora toolboxes (also, introducing tlbx)

### ISSUE THREAD

**Issue by uppercat** [containers/toolbox#350]
So, the toolbox idea is fascinating. But, being locked to Fedora toolboxes on a Fedora host is limiting. Looking over the issues, seems there are others who are looking for a more versatile solution.

As for the current state of toolbox:
1. The `init_container` and `mount_bind` functions run in the container. They are scattered with GNUisms that break in a busybox environment (i.e. Alpine) and are easily replaced.
2. The packages and docs in `extra-packages` and `missing-docs` are really not necessary for the toolbox experience. I mention this because not having to build a special image for every flavor of toolbox would be a plus.
3. Checking for bash or zsh in `toolbox.sh`, again not needed. Also, trying to force bash as a fallback causes pain for busybox.
4. The sourcing of `os-release` and the stuff with PLATFORM_ID serves questionable purpose and makes trouble outside of Red Hat distros.
5. In general toolbox tries to verify a lot of things that it doesn't need to (because podman will catch them).

I worked on making the script more general, but it's pretty intractable without major changes. Maybe you have no intention of changing any of these things.

Rather than throw a bunch of confrontational PRs at you, I had my own take on the problem: **[tlbx](https://gitlab.com/uppercat/tlbx)**. It's suiting my needs and others might find it helpful, so I'm sharing it here.

**Comment by debarshiray** [comment]
>     1. The `init_container` and `mount_bind` functions run in the container. They are
> scattered with GNUisms that break in a busybox environment (i.e. Alpine) and are easily
> replaced.

Interesting. I am curious about these GNUisms. `/usr/bin/toolbox` is currently a POSIX shell script, not a Bash script, and we use [ShellCheck](https://www.shellcheck.net/) to catch any deviations. I wonder if some mistakes might have crept in.

Anyway, @HarryMichal is currently working on [rewriting Toolbox in Go](https://github.com/containers/toolbox/pull/318), so these issues will soon go away.

>     2. The packages and docs in `extra-packages` and `missing-docs` are really not necessary
> for the toolbox experience. I mention this because not having to build a special image for every
> flavor of toolbox would be a plus.

Yes, I don't disagree. But ...

The primary goal of Toolbox is to provide an interactive debugging and development environment on OSTree-based operating systems where the host OS is meant to be locked down. So it provides a separate package-based mutable `/usr` and friends, where you can install your compilers, editors and SDKs to get your hacking done.

A typical use-case is a Endless OS or Silverblue user who is also a hacker. Such a user will spend a considerable amount of time inside a Toolbox environment. So we don't want to burden them too much with the additional cognitive load of being aware of the OCI container, because they didn't explicitly go out and ask for a container-based environment. They asked for a stable and secure OS, and got something that's supposed to be better than the old Fedora they were familiar with. However, it's going to be annoying if it gets too much in the way.

However, the base images of various distributions are optimized for size, not long-term interactive use. Missing documentation, missing utilities, sometimes cut down versions of familiar utilities (eg., `coreutils-single` versus `coreutils-full`) and so on. Some of these differences aren't that straightforward for an end-user to resolve.

Sometimes, Toolbox itself needs the image to be configured in a certain way or have certain utilities present.

A different approach could be to teach Toolbox itself to configure different OS images by installing the necessary packages and such on the fly. However, then it sort of becomes the responsibility of the core Toolbox maintainers to maintain this *support* for different distributions because *the support* lives within the `/usr/bin/toolbox` code.

The current approach takes the strategy of delegating this work to the distributions themselves by clearly documenting what the `/usr/bin/toolbox` code expects so that the distribution maintainer can come up with an OCI image or host configuration that meets those requirements.

Maybe there're other ways to do it? In the end, it's about going for the best compromise.

>     3. Checking for bash or zsh in `toolbox.sh`, again not needed. Also, trying to force bash as
> a fallback causes pain for busybox.

Bash is usually the default shell on most distributions, which is why it's used as the fallback. We can certainly think of ways to accommodate different fallback options for distributions that don't default to Busybox.

Currently, if your default shell on the host is BusyBox, then Toolbox will use BusyBox once you have installed it inside the toolbox container.

Could you describe your use-case in more detail?

>     4. The sourcing of `os-release` and the stuff with PLATFORM_ID serves questionable
> purpose and makes trouble outside of Red Hat distros.

Those are [systemd concepts](https://www.freedesktop.org/software/systemd/man/os-release.html), and systemd is pretty widely used these days to put together a Linux distribution.

What's your specific use-case?

>     5. In general toolbox tries to verify a lot of things that it doesn't need to (because podman
> will catch them).

Could you give some examples?

There are cases where Toolbox works around bugs in Podman, or avoids relying on some new convenience feature to avoid requiring a newer Podman, and so on. However, I don't know what you have in mind.

> Rather than throw a bunch of confrontational PRs at you, I had my own take on the
> problem: **[tlbx](https://gitlab.com/uppercat/tlbx)**. It's suiting my needs and others might
> find it helpful, so I'm sharing it here.

Interesting. Thanks for getting in touch!

**Comment by debarshiray** [comment]
It's been a while. We can certainly revisit this in the future if concrete and actionable use-cases show up.

Closing.
