### ISSUE TITLE
a clearer documentation about /var/home/user and /home/user directories

### ISSUE THREAD

**Issue by yilkalargaw** [containers/toolbox#352]
In fedora silver blue the containers use ```/home/user``` as their home directory while the host uses ```/var/home/user``` as the home directory. This is a bit confusing since their contents look the same but they are different in a certain unclear ways. 

For example setting home to ```/var/home/user/``` inside my containers makes emacs start five times faster and it allows it to better identify the python virtual environment files. Other programs also become noticeably faster (eg nix, kakoune). 

So what  is the difference between the two locations. Is there a security problem if ```HOME=/var/home/user``` to the .bashrc file. I think there should be a documentation section explaining the purposes of the two directories.( If there is a documentation and I missed it I would be glad to be referred to it

**Comment by markstos** [comment]
The fact that there's a big speed difference makes me wonder if this is a "container escape vulnerability". I ran into something like with the `snap` format where referencing the snap binary through the hosts directory path bypassed the sandboxing from calling the same binary through the `snap` binary. 

There *is* documentation about why `/var/home` is used on the host, which I found by searching for [silverblue /var/home].  Inside the containers the full container is read/write, which is why `/home/user` is used there. The more interesting question is why the performance difference between using the two different paths?

**Comment by debarshiray** [comment]
The `/var/home/user` and `/home/user` confusion reminds me of https://github.com/containers/toolbox/issues/262 but the performance problem is new.

OSTree-based OSes like Silverblue use `/var` because along with `/etc`, it's one of the few top-level filesystem hierarchies that aren't read-only. So putting your home directories under `/var` is convenient. There's a `/home` to `/var/home` symbolic link in place for backwards compatibility.

Toolbox tries to mimic the host's `$HOME` setup inside the container when creating it. On a Silverblue host, the container's `$HOME` is set to `/var/home/user`, and a `/home` to `/var/home` symbolic is created.

However, there had been some changes in this area. Before version 30, Silverblue would set `$HOME` to point inside the `/home` symbolic link instead of `/var/home`. So containers created with that version of the host OS might have `/home/user` as `$HOME`, which might be your case?

Anyway, this symbolic link has created problems in the past, especially prior to the above change in Silverblue 30, where subtle bugs would creep in due to not handling it properly. Here's one example: https://gitlab.gnome.org/GNOME/gdm/merge_requests/4

Nowadays with `$HOME` always pointing inside `/var/home`, nothing should be using the `/home` symbolic link, except old configuration and terribly broken code that just assumes `/home`.

As to the performance issue, you could try to `strace` the programs and see what's going on underneath.

**Comment by yilkalargaw** [comment]
thanks a lot. I was using fedora 30 and switching to fedora 31 helped
