### ISSUE TITLE
Being in a toolbox breaks Ctrl-p for readline

### ISSUE THREAD

**Issue by srbaker** [containers/toolbox#394]
I use the readline commands for navigating my command history in bash. That is: C-p for previous, C-n for next. C-p should do the same thing as up-arrow, and C-n should do the same as down-arrow.

When I am in a toolbox and I press C-p to get my previous command, nothing shows up. If I press return, the command shows up, and executes, but it was not visible until I press return. If I press C-p twice, I see the two-commands-ago command line, and then pressing C-n gives me the previous command.

This only happens when I am inside a toolbox on Fedora Silverblue. I have not tried it on other platforms. It does not happen on the same machine, when I am _not_ in a toolbox.

up-arrow and down-arrow work just fine.

**Comment by srbaker** [comment]
Sorry, a detail I forgot to mention: pressing C-p repeatedly, only every other press works.

If I have the following command history:

```
echo foo
echo bar
echo baz
echo qux
```
The following sequences happen:
C-p shows me nothing. Pressing return runs `echo qux`

C-p C-p shows `echo baz`. Then C-n will show `echo qux`.

C-p C-p C-p shows `echo baz`, but pressing return changes it to `echo bar` and runs that.

**Comment by EnigmaCurry** [comment]
I've been researching this myself and I know how to fix it.

Podman has a feature called detaching that listens for a key sequence and then detaches the tty from the running container. By default, that key sequence is "ctrl-p, ctrl-q". The problem has been that there was no way to turn this feature off (the best you could do was assign a different key sequence, but not turn if off entirely.) 

This is a bug fixed in podman 1.8.2 : https://github.com/containers/libpod/pull/5203 - you can now set the key sequence to the empty string (--detach-keys="") and this will completely disable the detach feature.

Toolbox needs a change to specify the detach-keys for podman. Here is my fork that is tested working, but it could likely be made more robust/configurable. https://github.com/EnigmaCurry/toolbox/commit/2baf60fc8ecfbf1a73a65c697d1f112009c9e75c

I will look into what it takes to open a PR for this...
