### ISSUE TITLE
Desktop files integration

### ISSUE THREAD

**Issue by ghost** [containers/toolbox#417]
If you install an GUI App (for example VS Code, GNOME Builder, et cetera), it will create desktop file in /usr/share/applications. But toolbox have isolated system (except homedir) and it will not bind.
If there can be an option to create desktop file from it like:
`$ toolbox desktop code.desktop` will do:

1. Copy /usr/share/applications/code.desktop to .local/share/applications/toolbox_code.desktop
2. Change all executable references (/usr/bin/code or code) to the conainers (/usr/bin/code -> toolbox run /usr/bin/code et cetera)
3. Copy icon to local icon storage

Also add option to remove:
`$ toolbox desktop code.desktop -r`
to remove ~/.local/share/applications/toolbox_code.desktop and the icon

**Comment by HarryMichal** [comment]
Hi @oksoft-git! This looks interesting. I was thinking of providing something similar to this. Would you want to make a PR with this feature (but not in Shell but in Go for the [new version of Toolbox](https://github.com/containers/toolbox/issues/318)?

@debarshiray, what do you think?

**Comment by oksoft-git** [comment]
> Hi @oksoft-git! This looks interesting. I was thinking of providing something similar to this. Would you want to make a PR with this feature (but not in Shell but in Go for the [new version of Toolbox](https://github.com/containers/toolbox/issues/318)?
> 
> @debarshiray, what do you think?

Sorry, I am rather Rustacean than Gopher... 😕

**Comment by oksoft-git** [comment]
I'm GOing for it!

**Comment by sandorex** [comment]
This feature would greatly benefit silverblue users cause then you can easily use applications from the container

Would it be possible to include basic binary integration, to allow it to export basic command wrappers to the base system or is that out of the scope for the project?

**Comment by HarryMichal** [comment]
Hi @sandorex ! The feature you are talking about is already being tracked here: #145. It is one of the priorities after rolling out the updated Toolbox. While these two features are a similar, the solution to them is very different.

I'm wondering now if giving Toolbox the power to create/edit .desktop files for apps is really the way to go. It would require Toolbox to know where to locate the existing .desktop file, find the right lines, update them and move/copy the file to a location where the desktop (not everybody uses GNOME Shell) will find it and use it. This seems to me as unnecessarily big chunk of logic that wouldn't come to much use.

Instead section in the documentation with instructions how to update an existing .desktop file sounds better to me.

If I'm wrong about the complexity, then, please, prove me wrong.

**Comment by sandorex** [comment]
Maybe this responsibility should be given to another application?
An application that gets all the applications (all the wanted ones) from selected toolbox containers and puts them in `~/.local/share/applications/toolbox_container_XXX` ?

(note that im throwing ideas around)

**Comment by ondra05** [comment]
https://github.com/ondra05/toolbox

**Comment by ondra05** [comment]
It is almost done, but I cannot extract icon path from desktop file to copy to host.

**Comment by ondra05** [comment]
Well, I have it. [github.com/ondra05/toolbox-desktop](https://github.com/ondra05/toolbox-desktop)

**Comment by sandorex** [comment]
@ondra05 Great work!

There's one thing that i personally would improved (it's not necessary though) and that is using `cat` to read the file from the container, it will work fine but its kinda hacky, cause `podman` shares images with `toolbox` you can use `podman cp` to copy files between container and the host

**Comment by A6GibKm** [comment]
I been toying with this idea in [this](https://github.com/A6GibKm/silverblue-tools/blob/master/toolbox-export) python script. Currently it install desktop files, icons, mime and metainfo. I have yet to add a uninstall feature, but doesn't seem too hard.

**Comment by sandorex** [comment]
I sadly dont have the time to do a proper app, i've made the UI but GTK is just pain in the ass, ill probably do CLI only app someday (hopefully)

**Comment by A6GibKm** [comment]
> I sadly dont have the time to do a proper app

I think that a GUI for this is overkill. Imho this should be handled with commands in the direction of `toolbox export` with flags as `--remove` and `--list`.

I will try to look into it. I wonder if it is possible to just add a `toolbox export APP` command that calls, say, this python script inside the toolbox in a similar fashion to `toolbox run export.py ARGS`. While it is clearly better to do it in go, this only involves copying files from toolbox's `/usr` to `$XDG_DATA_DIR` and it might be simpler to use a script for it. I don't know what the maintainer this of this possibility.

Note that such extension would have to take many things into account, the problem of handling icons is non-trivial for example.

**Comment by debarshiray** [comment]
This is similar to the discussion around the [addition of the run command](https://github.com/containers/toolbox/pull/76), including this IRC conversation from `#silverblue` on Freenode:
```
From #silverblue on Freenode:

15:56 <rishi> otaylor: alexlarsson: Hey! Do you have any thoughts on            
      https://github.com/debarshiray/toolbox/pull/76 ?
15:57 <rishi> In short, people want to be able to do "toolbox run emacs".
15:57 <rishi> And I am worried about encroaching on Flatpak territory.
15:58 <alexlarsson> I don't think its a huge problem.
15:58 <otaylor> rishi: I suspect we need such functionality if we want the      
      toolbox to be a serious tool that people rely on
15:58 <alexlarsson> No 2 tools will be 100% non-overlapping
15:59 <alexlarsson> and i can imagine using this in non-flatpak like way
15:59 <alexlarsson> toolbox run some-service
15:59 <otaylor> rishi: I'd be more worried about adding, say, menu item         
      management so that it looks like 'toolbox run emacs' is a real app
16:00 <alexlarsson> I mean, some people use flatpak for cli stuff
16:00 <rishi> otaylor: alexlarsson: Okay!
16:00 <alexlarsson> which is not quite the point
16:00 <alexlarsson> Still, it works
16:01 <alexlarsson> The main thing is that the design decisions that drive      
      toolbox and flatpak are driven by a particular usecase
16:01 <alexlarsson> Not that they can't be used other ways
16:03 <rishi> Yeah, toolbox is very clearly: "use jhbuild on Silverblue".
16:04 <rishi> walters would say "separate development prefix", but that's       
      about it, I think.
```

It's already possible to add `toolbox run emacs` in the *.desktop* file for the application installed inside the container. Having a command that actually parses and creates *.desktop* files is another step in that same direction, and I am not sure if it's one step too far.

**Comment by A6GibKm** [comment]
@debarshiray what do you think of a python script that copies desktop files, icondata and metadata? I already made one and it is working just fine.

**Comment by debarshiray** [comment]
It's definitely one way to go about it. However, I am hesitant to include it in Toolbox right now.

**Comment by apoos-maximus** [comment]
I am interested in working on  this issue !

**Comment by bam80** [comment]
>...
> not everybody uses GNOME Shell
...
> If I'm wrong about the complexity, then, please, prove me wrong.

@HarryMichal I believe your concerns are unnecessary.
Nowadays .desktop files and icon file themes are designed to be desktop-agnostic and subjected to [XDG Specs](https://www.freedesktop.org/wiki/Specifications/):
https://specifications.freedesktop.org/
https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

To all:
can we design needed functionality as `DNF` plugin maybe?

**Comment by bam80** [comment]
> I have yet to add a uninstall feature, but doesn't seem too hard.

Thanks @A6GibKm, please do! :)

**Comment by debarshiray** [comment]
This sounds a lot like replicating things that Flatpak already does and is designed to do.

I know that the presence of `toolbox run ...` makes it tempting to have deeper integration for graphical applications, but we don't want to get into handling desktop files. `toolbox run ...` is meant to facilitate things like creating your own custom desktop file that fires up a graphical Emacs instance running inside a specific container. It's a thin wrapper around `toolbox enter`, but I'd be careful about heading too far in that direction.

In general, Podman (or an OCI container) is a bad option for running GUI apps. That's the whole reason why Flatpak exists. Is there a specific reason or a specific graphical application that you want or need to run inside a Podman container?

I have one pet complaint called *devhelp*. I want the devhelp Flatpak to pick up documentation that might be installed in a Toolbox container's `/usr/share/gtk-doc`, but there might be ways to fix it.

Anyway, I am closing this now, because this isn't at the top of our priority list.

**Comment by bam80** [comment]
FYI I often make a container just to install 1 GUI app - if there is no flatpak for the app available, it's much easier than build one.

**Comment by alvarlagerlof** [comment]
I don't want to have to use something like this, but I just want vscode to work more out of the box with flatpak somehow. I currently run it in toolbox and have created a desktop file for it, but that is a hassle especially with icons.

**Comment by lachmanfrantisek** [comment]
> Is there a specific reason or a specific graphical application that you want or need to run inside a Podman container?

To give one example, for some time I use a toolbox with PyCharm and other developer tools and Project dependencies. The PyCharm flatpak does not allow me to enhance the environment as I would like to (i.e. install the Fedora packages) to be able to run/test/debug the developed project.

Desktop integration will be handy, but not necessary.

**Comment by debarshiray** [comment]
Yes, the problem with bridging Flatpak:ed IDEs with other tools and code in a Toolbox is a very valid one, and keeps coming up.

GNOME Builder is a very container-aware IDE, so it does know how to develop against containers (both Flatpak and Podman), but most IDEs out there aren't like that.

For Visual Studio Code various people have tried to use VS Code extensions to set up a bridge, and @owtaylor has been investigating this a bit in the past.

So, yes, known problem, needs more research and work, but the likely solution is probably not to teach Toolbox how to handle desktop files and icons.

**Comment by alvarlagerlof** [comment]
> So, yes, known problem, needs more research and work, but the likely solution is probably not to teach Toolbox how to handle desktop files and icons.

Reasonable. I understand the problems with doing this. Hope the IDE situation gets better.

**Comment by dinhokusanagi** [comment]
Desktop files integration, It would be perfect, in many situations much better than FlatPak.

**Comment by mpolden** [comment]
I also wanted to have Emacs inside Toolbox to access development tools and LSP servers. However, I didn't get Emacs to work exactly how I wanted (HiDPI issues) so instead I did the following:
- Layer the `emacs` package (I'm using Fedora Kinoite)
- Install the LSP servers I want inside a Toolbox: `dnf install gopls python3-lsp-server`
- Configure Eglot to run LSP servers through Toolbox:
```elisp
(defun toolbox-command (program)
  ;; cannot use toolbox run directly because it enforces --tty
  ;; switch to toolbox run when 0.0.99.4 moves to stable:
  ;; https://bodhi.fedoraproject.org/updates/FEDORA-2023-992b8bea0b
  ;; https://github.com/containers/toolbox/issues/157
  (list
   "podman" "--log-level" "error" "exec" "--interactive" "--user" (user-login-name) "fedora-toolbox-37" program))

(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               `(go-mode . ,(toolbox-command "gopls")))
  (add-to-list 'eglot-server-programs
               `(python-mode . ,(toolbox-command "pylsp"))))
```
- Emacs will then run these LSP servers inside Toolbox
- There's also https://github.com/fejfighter/toolbox-tramp for more complete Toolbox support.

**Comment by warpedgeoid** [comment]
So, it's OK to make user's lives more difficult because of an ideal? I love Flatpak, use it for pretty much everything from that I can, but it doesn't have the required permissions model to support many types of apps. Someone already mentioned IDEs and developer tools. Another area where it falls short is web browsers with support for external password managers like 1Password. All of these work just fine in a toolbox and this resistance to supporting exports is really perplexing given that it's the only sane option for those running immutable distros. I shouldn't need to reboot by system for simple app updates but that what layering forces us to do.

**Comment by samgarmany** [comment]
I agree, it's been four years and we still haven't found a solution to the IDE problem. Toolbox may not be the solution here forever but as we look towards the future of atomic desktops we need to bridge the gap between classic desktops and immutable ones. Occasionally IDEs like VSCode, or the Jetbrains suite expect to be run in a traditional userspace. Flatpak is great because the ostree image keeps the app secure and unchangable but that fails users when apps need packages installed in the same container. 

The nature of this problem means that only developers would utilize such a feature and are ideally the group understanding the impacts of that choice. I think for the sake of development on immutable desktops we need to offer users a safer containerized traditional experience if they really need.

With feature parity, Toolbox as a project could be widely adopted in the same way as Distrobox is, with it's better performance and Go.

**Comment by warpedgeoid** [comment]
Well said, @samgarmany. It seems like Flatpak is still years away from handling these cases and while I'd like to be fully Flatpak for GUI apps, that's just not possible at the moment. I know that you can use `toolbox run`, but it's not very elegant nor discoverable.

I think another consideration is that Distrobox may not be installable by users in some corporate environments. Toolbox comes in the box with Silverblue which makes it much easier for some folks. Deskop exports and custom homedirs are really the only reasons that anyone should want to use Distrobox.

**Comment by svenjacobs** [comment]
I'm very disappointed that the `toolbox` devs hesitate to implement an easy export functionality of GUI applications 🙁

There are still situations where Flatpak isn't the solution for everything. For example when you want to install your password manager and browser both via Flatpak but they can't communicate with each other because of restrictions & limitations.

Since `toolbox` comes with Fedora Silverblue preinstalled, it would be a nice solution for this problem, but I also don't want to deal with copying and creating desktop files myself. I guess I have to resort to `distrobox` then 😔
