### ISSUE TITLE
run Desktop Environment from within Toolbox

### ISSUE THREAD

**Issue by bam80** [containers/toolbox#419]
Hi, there is instruction how to run Gnome in Toolbox, in separate and nested sessions:
https://blogs.gnome.org/fmuellner/2020/03/02/shell-hacking-on-silverblue/
I'm curious what is needed to do the same with KDE Plasma? Any advice?
Thanks

**Comment by HarryMichal** [comment]
Hi @bam80! Toolbox is a tool that isn't bound to any project/software specifically. There are many use cases and it is impossible for us to give instructions for most of them. TLDR; I don't know how to do the same thing for Plasma :-).

You could go through the scripts that Florian made and compare them with the tools/workflows that are used for Plasma's development. But it *should* work because it works for Shell. Good luck.

**Comment by bam80** [comment]
Thank for reply @HarryMichal ! I'm new to Toolbox so I need to be brave )
