### ISSUE TITLE
improve container initalization error message

### ISSUE THREAD

**Issue by FlorianLudwig** [containers/toolbox#443]
I am trying to build my own image to use with toolbox.  Sadly it didn't work.  This issue is not about my image not working but about the error message:

```
$ toolbox create -c test --image test
Created container: test
Enter with: toolbox enter --container test

$ toolbox enter --container test
toolbox: failed to initialize container test
```

The message `failed to initialize container` does not help debugging and there is no `--verbose`. Therefore I propose including what failed in the error message.

**Comment by HarryMichal** [comment]
Hi @FlorianLudwig! Yes, this is something that we sorely need and I want to work on it in the future. Or if you are interested, you can take a shot at it! We already landed the rewritten Toolbox and the codebase should be ready to be hacked on.

**Comment by debarshiray** [comment]
Well, there's definitely a `--verbose` flag. :)

The actual initialization happens in a different process running inside the toolbox container. It's actually the entry point of the container. So, if you want to see what's happening inside it, you can try:
```
$ podman start --attach <container>
```

**Comment by debarshiray** [comment]
Having said that, it would be nice to tunnel the output of the entry point running inside the toolbox container to the `toolbox enter` command. However, I don't think anyone is working on it at the moment.

Feel free to submit a separate issue if you have any ideas.

I am closing this one, because, even though non-ideal, there's already a way for developers to look at the initialization sequence.
