### ISSUE TITLE
RFE: overlaid toolbox by convention

### ISSUE THREAD

**Issue by langdon** [containers/toolbox#462]
I assume most people update / overlay the default toolbox with something as simple as "dnf update" but probably with a set of installed software. I think it would be nice if toolbox chose a container name like "my-toolbox" that it tested for before launching the generic toolbox.  In other words, I launch a toolbox, dnf update, install my stuff, podman commit that toolbox, then tag it "my-toolbox." After that, toolbox would use the "my-toolbox" container image by default and fail over to the default toolbox.

**Comment by debarshiray** [comment]
Interesting.

I wonder if it already works if you `podman commit` your custom image as `localhost/fedora-toolbox:32` or (just `fedora-toolbox:32` because `localhost` will get prefixed anyway)?

By default, Toolbox uses an image called `fedora-toolbox:N`. It first looks for it in the `localhost` registry, and only if not found consults at the Fedora registry.

So, this might already somewhat work, but I haven't tested this exact use-case or scenario.

**Comment by debarshiray** [comment]
ping

**Comment by langdon** [comment]
this does work. You must tag it as "32" (or whatever version you are using). I also tried "latest" which did not work.

**Comment by debarshiray** [comment]
Yes, Toolbox tries to avoid the `latest` tag because it makes it difficult to know what's exactly inside. Developers using Toolbox would want to know if it's a Fedora 35 container or a Fedora 34 or something else.

Anyway, thanks for trying it out. I am glad it works for you.

I am closing this since it already somewhat works.
