### ISSUE TITLE
vscode extension?

### ISSUE THREAD

**Issue by Yajo** [containers/toolbox#610]
**Is your feature request related to a problem? Please describe.**
I love toolbox but I don't use it daily because I'd have to type `toolbox enter` every time.
I develop mainly from vscode and I'd love it if there were a way for it to work always inside the toolbox. Or at least to do it by default.
[VSCode supports remote development](https://code.visualstudio.com/docs/remote/remote-overview), and one of the specifically supported environments are [containers](https://code.visualstudio.com/docs/remote/containers-tutorial).

**Describe the solution you'd like**
I'd like it a lot if there was a "Remote - toolbox" extension that, once installed, lets you just choose the toolbox name for your environment (if you want; otherwise just use default one). Then that would make VSCode do all of its stuff inside the toolbox and not outside of it.

**Describe alternatives you've considered**
Using the above linked containers extension to configure it to develop inside toolbox, but I don't think it's possible. If it were, some docs on how to do that would be just enough.

**Comment by lbssousa** [comment]
Related issue on the other side: https://github.com/microsoft/vscode-remote-release/issues/3345

**Comment by lbssousa** [comment]
There's a PR open here that allows connecting VSCode easily to a Toolbox container via Remote-SSH extension. Another possible approach would be to make toolbox able to export a suitable devcontainer.json file for use with Remote-Containers extension.

**Comment by debarshiray** [comment]
> There's a PR open here that allows connecting VSCode easily to
> a Toolbox container via Remote-SSH extension.

Yes, that's https://github.com/containers/toolbox/pull/587

**Comment by debarshiray** [comment]
Let's close this issue and follow-up in the other respective issues.

**Comment by lbssousa** [comment]
I was able to connect to my Toolbox container through VSCode's Remote-Containers extension. All I have to do is:
* Provide a file `$HOME/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs/${TOOLBOX_CONTAINER_NAME}.json` like this:
```
{
  "remoteUser": "${localEnv:USER}",
  "remoteEnv": {
    "COLORTERM": "${localEnv:COLORTERM}",
    "DBUS_SESSION_BUS_ADDRESS": "${localEnv:DBUS_SESSION_BUS_ADDRESS}",
    "DESKTOP_SESSION": "${localEnv:DESKTOP_SESSION}",
    "DISPLAY": "${localEnv:DISPLAY}",
    "LANG": "${localEnv:LANG}",
    "SHELL": "${localEnv:SHELL}",
    "SSH_AUTH_SOCK": "${localEnv:SSH_AUTH_SOCK}",
    "TERM": "${localEnv:TERM}",
    "VTE_VERSION": "${localEnv:VTE_VERSION}",
    "XDG_CURRENT_DESKTOP": "${localEnv:XDG_CURRENT_DESKTOP}",
    "XDG_DATA_DIRS": "${localEnv:XDG_DATA_DIRS}",
    "XDG_MENU_PREFIX": "${localEnv:XDG_MENU_PREFIX}",
    "XDG_RUNTIME_DIR": "${localEnv:XDG_RUNTIME_DIR}",
    "XDG_SESSION_DESKTOP": "${localEnv:XDG_SESSION_DESKTOP}",
    "XDG_SESSION_TYPE": "${localEnv:XDG_SESSION_TYPE}",
  }
}
```
* Give write permission to container's `/root` folder for my user, since current Remote-Containers will try to install `.vscode-server` folder there.

I'm currently unable to ensure that my shell in VSCode is started as `capsh --caps= -- -c 'exec "$@"' /bin/sh [my-login-shell]`, like `toolbox run|enter` does. Is it really needed?

**Comment by lbssousa** [comment]
@debarshiray from my regular tests here, the settings above are enough to allow me to work comfortably within a Toolbox container via VSCode's Remote-Containers extension. You may consider adding a feature to `toolbox` binary that automates these settings.

**Comment by romahicks** [comment]
Foremost, I am not a VSCode power user and don't have complex setups or code projects.
But on Fedora 34, if I install `podman-docker` packages.  VSCode interacts with podman as though it were docker and so far hasn't required me to make in adjustments in the environment; tested in Go and Rust build toolboxes. Although, I noticed that VSCode runs as root in the toolbox so that could be a security concern for some.
