### ISSUE TITLE
Can't operate toolbox after update

### ISSUE THREAD

**Issue by hadess** [containers/toolbox#647]
```sh
$ toolbox create -r 34
$ toolbox enter -r 34
$ sudo cat /etc/sudoers
[content of the sudoers file...]
$ sudo dnf builddep -y gnome-bluetooth
[...]
Complete!
$ sudo cat /etc/sudoers
hadess is not in the sudoers file.  This incident will be reported.
```

**Comment by debarshiray** [comment]
It might have been a passing RPM packaging problem in Fedora Rawhide, because I failed to reproduce it.

The `sudo` access in Toolbox containers works by having the user placed in the `wheel` group:
```
⬢[rishi@toolbox ~]$ cat /etc/group | grep wheel
wheel:x:10:rishi
```

Did that somehow go missing during the DNF transaction? In my case, it didn't, my user was still a part of `wheel`.

**Comment by debarshiray** [comment]
@HarryMichal confirmed that it was a passing bug in Fedora Rawhide that has since been fixed. We couldn't dig up a bug reference, though.

**Comment by hadess** [comment]
It was https://bugzilla.redhat.com/show_bug.cgi?id=1906066

**Comment by debarshiray** [comment]
Thanks for digging that up, @hadess !

**Comment by dabrain34** [comment]
See https://github.com/containers/toolbox/issues/1361
