### ISSUE TITLE
enable project wiki?

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#759]
https://github.com/containers/toolbox/wiki doesn't seem to work?
It could be useful for documenting various tweaks/hacks/OSes etc

**Comment by HarryMichal** [comment]
Maybe we could even use it as the main wiki... It's just a matter of writing the docs :)

**Comment by juhp** [comment]
Thank you for making this available finally!

**Comment by debarshiray** [comment]
*Summarizing my earlier discussion with @HarryMichal and @olivergs from a few months ago.  I realized that I never commented here.  I apologize for that.*

What's the purpose of having a wiki?

I think that a wiki is not a good idea at this point, because it adds yet another source of truth for the documentation.  In short, we should polish our existing documentation instead of adding more and more sources for it that diverge over time and we can no longer keep track off.

Over time, our documentation has fractured across multiple wikis and platforms.  For a project that's relatively new and small, this is a problem, because it prevents us from quickly changing things, whether it's our branding, our command line interface, the direction of the project, etc..

Here are the other wikis and documentation platforms that we have used in the past:
* https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/
* https://fedoraproject.org/wiki/Workstation/Desktop_Containers

... and I think we should take them down after finding ways to absorb them into our documentation.

This is why, we had decided in one of our calls that we will consolidate as much as possible (if not everything) in our manuals.  Our manuals are written in Markdown, so they are web-friendly, and are shipped as part of Toolbox itself.  The `README.md` is the landing page for the GitHub repository, so we can find ways to lead the reader from further into the documentation.  We also have a `CONTRIBUTING.md`.

This is not without precedent. eg., look at systemd.  They seem to be able to pack a significant amount of information in their [manuals](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html), and systemd is a much bigger project than Toolbox.  In fact, as per their [README.md](https://github.com/systemd/systemd/) systemd seems to have deprecated their [wiki](https://github.com/systemd/systemd/).

Another example is Flatpak, which is also a much bigger project than Toolbox.

On top of that, Toolbox now has a [website](https://containertoolbx.org/), and right now, our wiki only repeats what's already there.

If there's a need to document tweaks, hacks or other interesting pieces of information, then we can find other ways of advertising them.  eg., Flatpak's website links to [blog posts](https://flatpak.org/blog-posts/) and [presentations](https://flatpak.org/presentations/).  In general, it will be wise to not sound too official when documenting tweaks and hacks, because people will start relying on them and they won't be tweaks and hacks anymore.

**Comment by debarshiray** [comment]
I filed a [request](https://github.com/containers/containertoolbx.org/issues/5) to add pages to track blog posts and presentations on the Toolbx [website](https://containertoolbx.org/).

**Comment by debarshiray** [comment]
Disabled wiki. The [website](https://containertoolbx.org/) now has a section for articles, blogs and presentations.

**Comment by juhp** [comment]
Maybe I can just drop a plug here for https://github.com/toolbox-images/toolbox-images where the community can experiment with alternative image ideas for toolbox (with some of the kind of things I originally had envisaged maybe being in the wiki), though of course people are keen to get their changes and ideas into toolbox itself.

**Comment by debarshiray** [comment]
Sure, people can play with their own images and advertise them through their blogs, and we can link to them from our website. Diversity in an ecosystem is usually a good thing.

However, it won't be prudent to suggest any level of *official* support for an OS distribution unless we have some serious commitment from that community. eg., a maintainer with a `@debian.org` email for a Debian image. Each image is a mini-distribution, and in many cases bugs need to be fixed elsewhere, beyond Toolbox, within that distro. That's something that only people deeply involved with the distro can do.

I think it's reasonable to define *official* support as something that's directly hosted on the project's online real estate. eg., part of the Git repository, web pages, etc.. Linking to an external website, even from our own pages, can be considered as an indication of crossing that support boundary.

Ultimately, the `images` carried inside the Git repository are there for only one reason. To make it easier for contributors to get access to the *officially* supported images. Either for hacking on Toolbox or to use them as templates for other custom images. Having lots of different images with widely different support levels will cause confusion.
