### ISSUE TITLE
Fedora Tacklebox?

### ISSUE THREAD

**Issue by jwillikers** [containers/toolbox#790]
**Is your feature request related to a problem? Please describe.**

I'd love to have fish installed in the fedora-toolbox by default, since it's my primary shell.
I'm sure I am not the only one.

**Describe the solution you'd like**

I would like the `fedora-toolbox` image to include the fish shell.

**Describe alternatives you've considered**

The alternative I'm considering is to create `fedora-tacklebox`, an image based on `fedora-toolbox` which includes the fish shell.

**Comment by mfocko** [comment]
You can always run the image in podman, install whatever you want and commit that image, toolbox checks local image first… I have zsh, updates and setting up of local mirror done that way

**Comment by debarshiray** [comment]
@mfocko yes, exactly. :)

The other alternative is to take the image definition from the `image` sub-directory of `toolbox.git`, modify it as per your needs, build it with `podman build ...`, and Toolbox should pick it up.

The official images served from `registry.fedoraproject.org` aim to mimic the command line user experience of a default Fedora Silverblue or Workstation installation. It's done that way to strike a balance between image size and ease of use, because a bigger image means that every user needs to download more.

**Comment by debarshiray** [comment]
Closing.

Thanks for stopping by! :)
