### ISSUE TITLE
Toolbox detection

### ISSUE THREAD

**Issue by Enchufa2** [containers/toolbox#808]
I didn't find in the documentation anything related to reliably detecting that a script is running inside a toolbox. Is this possible? For my use case, it would be enough to know that `sudo` can be used without a password, but if I execute this:

```bash
⬢[toolbox]$ sudo -n true
sudo: a password is required
⬢[toolbox]$ echo $?
1
```

it seems that a password is required, but then I need no password inside the toolbox, so I'm a bit confused.

**Comment by olivergs** [comment]
You can check if  /run/.toolboxenv is present.

**Comment by Enchufa2** [comment]
Nice! Is this documented somewhere? (I.e., how likely is this to continue being present across toolbox releases? ;-) )

**Comment by HarryMichal** [comment]
> Is this documented somewhere? (I.e., how likely is this to continue being present across toolbox releases? ;-) )

The feature has been around since [v0.0.10](https://github.com/containers/toolbox/blob/e935ed893d5b72ac9f08987bc2c7ede9f7d506cc/NEWS#L252). The presence of the file is not mentioned in the manual pages in the latest release but it [is](https://github.com/containers/toolbox/blob/ea452d7ced8e798a8a2c1ae1fbdd34418dea9bc7/doc/toolbox-init-container.1.md#L59) mentioned in the current git version.

**Comment by HarryMichal** [comment]
I'll close this as this is not an issue. Thank you for reaching out @Enchufa2!
